package io.github.kimmandoo

const val DESKTOP_CONTENT_WIDTH = 1280
const val DESKTOP_CONTENT_HORIZONTAL_PADDING = 128
const val DESKTOP_CONTENT_VERTICAL_PADDING = 72
const val DESKTOP_CONTENT_MIN_HEIGHT = 768

const val TABLET_CONTENT_HORIZONTAL_PADDING = 64
const val TABLET_CONTENT_VERTICAL_PADDING = 48
const val TABLET_CONTENT_MIN_HEIGHT = 768

const val MOBILE_CONTENT_HORIZONTAL_PADDING = 24
const val MOBILE_CONTENT_VERTICAL_PADDING = 48
const val MOBILE_CONTENT_MIN_HEIGHT = 640

// TOPBAR
const val HEADER_HEIGHT = 72

// PADDING
const val MOBILE_DRAWER_PADDING_START = 80
