package io.github.kimmandoo.model

import kimmandoo_porfolio.composeapp.generated.resources.Res
import kimmandoo_porfolio.composeapp.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource
import org.jetbrains.compose.resources.StringResource

enum class Project(
    val titleRes: StringResource,
    val subtitleRes: StringResource,
    val graphicRes: DrawableResource,
    val periodRes: StringResource,
    val descriptionRes: StringResource,
    val roleRes: StringResource,
    val techStackRes: StringResource,
    val links: List<Link>,
    val contributionsRes: StringResource,
) {
    LINK_LETTER(
        titleRes = Res.string.project_link_letter,
        subtitleRes = Res.string.project_link_letter_subtitle,
        graphicRes = Res.drawable.ic_android,
        periodRes = Res.string.project_link_letter_period,
        descriptionRes = Res.string.project_link_letter_description,
        roleRes = Res.string.mobile_developer,
        techStackRes = Res.string.project_link_letter_techStack,
        links = listOf(),
        contributionsRes = Res.string.project_link_letter_contributions,
    ),
//    LUCKY_LOTTERY(
//        titleRes = Res.string.project_lucky_lottery,
//        subtitleRes = Res.string.project_lucky_lottery_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_lucky_lottery_period,
//        descriptionRes = Res.string.project_lucky_lottery_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_lucky_lottery_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_lucky_lottery_contributions,
//    ),
//    FRIENDOGLY(
//        titleRes = Res.string.project_friendogly,
//        subtitleRes = Res.string.project_friendogly_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_friendogly_period,
//        descriptionRes = Res.string.project_friendogly_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_friendogly_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_friendogly_contributions,
//    ),
//    MOVE_MOVE(
//        titleRes = Res.string.project_move_move,
//        subtitleRes = Res.string.project_move_move_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_move_move_period,
//        descriptionRes = Res.string.project_move_move_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_move_move_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_move_move_contributions,
//    ),
//    WHATNOW(
//        titleRes = Res.string.project_whatnow,
//        subtitleRes = Res.string.project_whatnow_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_whatnow_period,
//        descriptionRes = Res.string.project_whatnow_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_whatnow_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_whatnow_contributions,
//    ),
//    OH_SOON_TAXI(
//        titleRes = Res.string.project_oh_soon_taxi,
//        subtitleRes = Res.string.project_oh_soon_taxi_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_oh_soon_taxi_period,
//        descriptionRes = Res.string.project_oh_soon_taxi_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_oh_soon_taxi_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_oh_soon_taxi_contributions,
//    ),
//    KNOCKNOCK(
//        titleRes = Res.string.project_knocknock,
//        subtitleRes = Res.string.project_knocknock_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_knocknock_period,
//        descriptionRes = Res.string.project_knocknock_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_knocknock_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_knocknock_contributions,
//    ),
//    KORDLE(
//        titleRes = Res.string.project_kordle,
//        subtitleRes = Res.string.project_kordle_subtitle,
//        graphicRes = Res.drawable.ic_android,
//        periodRes = Res.string.project_kordle_period,
//        descriptionRes = Res.string.project_kordle_description,
//        roleRes = Res.string.android_developer,
//        techStackRes = Res.string.project_kordle_techStack,
//        links = listOf(),
//        contributionsRes = Res.string.project_kordle_contributions,
//    ),
}
